# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/david/Personal/Linux_Unreal_Engine_5.2.0
GAMEPROJECTFILE =/home/david/Documents/Unreal Projects/Chrono/Chrono.uproject

TARGETS = \
	Chrono-Linux-DebugGame  \
	Chrono-Linux-Shipping  \
	Chrono \
	ChronoEditor-Linux-DebugGame  \
	ChronoEditor-Linux-Shipping  \
	ChronoEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ChronoEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ChronoEditor-Linux-Debug


Chrono-Linux-DebugGame:
	 $(PROJECTBUILD) Chrono Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Chrono-Linux-Shipping:
	 $(PROJECTBUILD) Chrono Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Chrono:
	 $(PROJECTBUILD) Chrono Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChronoEditor-Linux-DebugGame:
	 $(PROJECTBUILD) ChronoEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChronoEditor-Linux-Shipping:
	 $(PROJECTBUILD) ChronoEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChronoEditor:
	 $(PROJECTBUILD) ChronoEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
